name: MacOS
on:
  schedule:
    - cron: '10 9 * * *'
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/MacOS.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/MacOS.yml'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      TEST_PREFERRED_CHAIN: (STAGING) Pretend Pear X1
      TEST_PROTOCOL_Server: "LetsEncrypt.org_test"
    steps:
    - uses: actions/checkout@v4
    - name: Install tools
      run:  brew update && brew install socat;
    - name: Run protocol.sh
      run: sudo --preserve-env ./letest.sh
