name: NetBSD
on:
  schedule:
    - cron: '10 9 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'protocoltest'
    paths:
      - '**.sh'
      - '.github/workflows/NetBSD.yml'
  pull_request:
    branches:
      - 'protocoltest'
    paths:
      - '**.sh'
      - '.github/workflows/NetBSD.yml'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  NetBSD:
    strategy:
      matrix:
        release: [""]
    runs-on: ubuntu-latest
    env:
      TEST_PREFERRED_CHAIN: (STAGING) Pretend Pear X1
      TEST_PROTOCOL_Server: "LetsEncrypt.org_test"
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/cf-tunnel@v0
      id: tunnel
      with:
        protocol: http
        port: 8080
    - name: Set envs
      run: echo "TestingDomain=${{steps.tunnel.outputs.server}}" >> $GITHUB_ENV
    - uses: vmactions/netbsd-vm@v1
      with:
        envs: 'TestingDomain TEST_PREFERRED_CHAIN TEST_PROTOCOL_Server'
        nat: |
          "8080": "80"
        prepare: |
          /usr/sbin/pkg_add curl socat
        usesh: true
        copyback: false
        release: ${{ matrix.release }}
        run: ./letest.sh
