name: Solaris
on:
  schedule:
    - cron: '10 9 * * *'
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/Solaris.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/Solaris.yml'


concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Solaris:
    strategy:
      matrix:
        release: [""]
    runs-on: ubuntu-latest
    env:
      TEST_PREFERRED_CHAIN: (STAGING) Pretend Pear X1
      TEST_PROTOCOL_Server: "LetsEncrypt.org_test"
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/cf-tunnel@v0
      id: tunnel
      with:
        protocol: http
        port: 8080
    - name: Set envs
      run: echo "TestingDomain=${{steps.tunnel.outputs.server}}" >> $GITHUB_ENV
    - uses: vmactions/solaris-vm@v1
      with:
        envs: 'TestingDomain TEST_PREFERRED_CHAIN TEST_PROTOCOL_Server'
        nat: |
          "8080": "80"
        prepare: pkgutil -y -i socat curl
        release: ${{ matrix.release }}
        copyback: false
        run: ./letest.sh
