name: Windows
on:
  schedule:
    - cron: '10 9 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'protocoltest'
    paths:
      - '**.sh'
      - '.github/workflows/Windows.yml'
  pull_request:
    branches:
      - 'protocoltest'
    paths:
      - '**.sh'
      - '.github/workflows/Windows.yml'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true


jobs:
  Windows:
    runs-on: windows-latest
    env:
      #The 80 port is used by Windows server, we have to use a custom port, ngrok will also use this port.
      Le_HTTPPort: 8888
      TEST_PREFERRED_CHAIN: (STAGING) Pretend Pear X1
      TEST_PROTOCOL_Server: "LetsEncrypt.org_test"
    steps:
    - name: Set git to use LF
      run: |
          git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - name: Install cygwin base packages with chocolatey
      run: |
          choco config get cacheLocation
          choco install --no-progress cygwin
      shell: cmd
    - name: Install cygwin additional packages
      run: |
          C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P socat,curl,cron,unzip,git
      shell: cmd
    - name: Set ENV
      shell: cmd
      run: |
          echo PATH=C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin >> %GITHUB_ENV%
    - name: Check ENV
      shell: cmd
      run: |
          echo "PATH=%PATH%"
    - name: Run protocol.sh
      shell: cmd
      run: bash.exe -c ./letest.sh
